export const urduDictionary: Record<string, string> = {
  // Common Verbs & Connectors
  "the": "یہ",
  "is": "ہے",
  "was": "تھا",
  "are": "ہیں",
  "be": "ہونا",
  "to": "کرنے",
  "a": "ایک",
  "an": "ایک",
  "and": "اور",
  "or": "یا",
  "of": "کا",
  "in": "میں",
  "on": "پر",
  "with": "کے ساتھ",
  "for": "کے لیے",
  "by": "کی طرف سے",
  "from": "سے",
  "as": "کے طور پر",
  "that": "کہ",
  "this": "یہ",
  "it": "یہ",
  "at": "پر",
  "about": "کے بارے میں",
  "but": "لیکن",
  "not": "نہیں",
  "can": "سکتا ہے",
  "will": "کرے گا",
  "has": "ہے",
  "have": "ہیں",
  "more": "زیادہ",
  "less": "کم",
  "all": "تمام",
  "most": "زیادہ تر",
  "some": "کچھ",
  "such": "ایسا",
  "very": "بہت",
  "also": "بھی",

  // Technical Terms
  "javascript": "جاوا اسکرپٹ",
  "programming": "پروگرامنگ",
  "language": "زبان",
  "function": "فنکشن",
  "variable": "ویری ایبل",
  "framework": "فریم ورک",
  "developer": "ڈیولپر",
  "application": "ایپلیکیشن",
  "web": "ویب",
  "frontend": "فرنٹ اینڈ",
  "backend": "بیک اینڈ",
  "code": "کوڈ",
  "coding": "کوڈنگ",
  "software": "سافٹ ویئر",
  "engineer": "انجینئر",
  "stack": "اسٹیک",
  "fullstack": "فل اسٹیک",
  "script": "سکرپٹ",
  "json": "جیسن",
  "api": "اے پی آئی",
  "database": "ڈیٹا بیس",
  "mongodb": "مونگو ڈی بی",
  "nodejs": "نوڈ جے ایس",
  "react": "ری ایکٹ",
  "component": "کمپوننٹ",
  "server": "سرور",
  "client": "کلائنٹ",
  "request": "درخواست",
  "response": "جواب",
  "fetch": "لانا",
  "parse": "تجزیہ کرنا",

  // Educational & Contextual
  "learn": "سیکھیں",
  "start": "شروع کریں",
  "course": "کورس",
  "tutorial": "سبق",
  "guide": "رہنما",
  "example": "مثال",
  "introduction": "تعارف",
  "summary": "خلاصہ",
  "explanation": "وضاحت",

  // Misc
  "free": "مفت",
  "tools": "اوزار",
  "easy": "آسان",
  "powerful": "طاقتور",
  "popular": "مقبول",
  "open": "کھلا",
  "source": "ذریعہ",
  "community": "کمیونٹی",
  "platform": "پلیٹ فارم",

  // Extra fallback
  "you": "آپ",
  "we": "ہم",
  "they": "وہ",
  "your": "آپ کا",
  "our": "ہمارا",
  "their": "ان کا",

  // Additional ~100 words
  "computer": "کمپیوٹر",
  "technology": "ٹیکنالوجی",
  "digital": "ڈیجیٹل",
  "network": "نیٹ ورک",
  "internet": "انٹرنیٹ",
  "email": "ای میل",
  "login": "لاگ ان",
  "logout": "لاگ آؤٹ",
  "user": "صارف",
  "account": "اکاؤنٹ",
  "password": "پاس ورڈ",
  "security": "سیکیورٹی",
  "privacy": "رازداری",
  "access": "رسائی",
  "permission": "اجازت",
  "file": "فائل",
  "folder": "فولڈر",
  "upload": "اپ لوڈ",
  "download": "ڈاؤن لوڈ",
  "search": "تلاش",
  "result": "نتیجہ",
  "error": "غلطی",
  "success": "کامیابی",
  "loading": "لوڈ ہو رہا ہے",
  "complete": "مکمل",
  "data": "ڈیٹا",
  "analytics": "تجزیات",
  "dashboard": "ڈیش بورڈ",
  "interface": "انٹرفیس",
  "design": "ڈیزائن",
  "performance": "کارکردگی",
  "speed": "رفتار",
  "responsive": "رد عمل ظاہر کرنے والا",
  "mobile": "موبائل",
  "desktop": "ڈیسک ٹاپ",
  "device": "آلہ",
  "support": "مدد",
  "bug": "نقص",
  "fix": "درست کریں",
  "update": "اپ ڈیٹ",
  "version": "ورژن",
  "build": "بنائیں",
  "deploy": "تقرر کریں",
  "hosting": "میزبانی",
  "domain": "ڈومین",
  "browser": "براؤزر",
  "tab": "ٹیب",
  "window": "ونڈو",
  "click": "کلک کریں",
  "submit": "جمع کریں",
  "form": "فارم",
  "input": "ان پٹ",
  "output": "آؤٹ پٹ",
  "value": "قدر",
  "key": "کلید",
  "type": "قسم",
  "object": "آبجیکٹ",
  "array": "ارے",
  "string": "سٹرنگ",
  "boolean": "بولین",
  "number": "نمبر",
  "true": "سچ",
  "false": "غلط",
  "null": "خالی",
  "undefined": "غیر متعین",
  "loop": "لوپ",
  "condition": "شرط",
  "if": "اگر",
  "else": "ورنہ",
  "switch": "سوئچ",
  "case": "کیس",
  "break": "وقفہ",
  "continue": "جاری رکھیں",
  "return": "واپسی",
  "export": "برآمد کریں",
  "import": "درآمد کریں",
  "default": "طے شدہ",
  "async": "غیر ہم وقت",
  "await": "انتظار کریں",
  "promise": "وعدہ",
  "resolve": "حل کریں",
  "reject": "رد کریں",
  "catch": "پکڑو",
  "then": "پھر",
  
  // Education & Learning
"education": "تعلیم",
"student": "طالب علم",
"teacher": "استاد",
"school": "اسکول",
"university": "یونیورسٹی",
"subject": "مضمون",
"exam": "امتحان",
"grade": "درجہ",
"certificate": "سرٹیفکیٹ",
"degree": "ڈگری",
"homework": "ہوم ورک",
"lecture": "لیکچر",
"assignment": "اسائنمنٹ",
"classroom": "کلاس روم",

// Business & Finance
"business": "کاروبار",
"money": "پیسہ",
"bank": "بینک",
"accounting": "اکاؤنٹنگ",
"finance": "مالیات",
"loan": "قرض",
"payment": "ادائیگی",
"salary": "تنخواہ",
"investment": "سرمایہ کاری",
"budget": "بجٹ",
"tax": "ٹیکس",
"profit": "منافع",
"loss": "نقصان",
"market": "بازار",

// Health & Medicine
"health": "صحت",
"doctor": "ڈاکٹر",
"hospital": "ہسپتال",
"medicine": "دوائی",
"disease": "مرض",
"treatment": "علاج",
"vaccine": "ویکسین",
"emergency": "ہنگامی",
"injury": "چوٹ",
"pain": "درد",
"checkup": "معائنہ",
"symptom": "علامت",
"diagnosis": "تشخیص",

// Geography & Travel
"city": "شہر",
"country": "ملک",
"continent": "بر اعظم",
"map": "نقشہ",
"travel": "سفر",
"flight": "پرواز",
"airport": "ہوائی اڈہ",
"ticket": "ٹکٹ",
"hotel": "ہوٹل",
"tourist": "سیاح",
"journey": "سفر",
"destination": "منزل",

// Literature & Language
"book": "کتاب",
"story": "کہانی",
"author": "مصنف",
"novel": "ناول",
"poem": "نظم",
"grammar": "قواعد",
"word": "لفظ",
"sentence": "جملہ",
"dictionary": "لغت",
"translation": "ترجمہ",
"literature": "ادب",

// Work & Productivity
"job": "نوکری",
"work": "کام",
"task": "کام",
"project": "منصوبہ",
"goal": "مقصد",
"deadline": "آخری تاریخ",
"meeting": "اجلاس",
"schedule": "شیڈول",
"report": "رپورٹ",
"presentation": "پریزنٹیشن",
"plan": "منصوبہ بندی",
"team": "ٹیم",
"manager": "مینجر",

"blog": "بلاگ",
"test": "امتحان",
"how": "کیسے",
"write": "لکھنا",
"clean": "صاف",
"simple": "سادہ",
"principles": "اصول",
"learning": "سیکھنا",
"important": "اہم",
"fast": "تیز",
"slow": "سست",
"tips": "مشورے",
"tricks": "چالاکیاں",
"best": "بہترین",
"beginners": "نئے سیکھنے والے",
"advanced": "اعلی",
"concept": "تصور",
"method": "طریقہ",
"system": "نظام",
"architecture": "فنِ تعمیر",
"secure": "محفوظ",
"blogs": "بلاگز",
"content": "مواد",
"indexing": "اندراج",
"index": "فہرست",
"engine": "انجن",
"engines": "انجنز",
"platforms": "پلیٹ فارمز",
"publishers": "اشاعت کنندگان",
"updates": "اپ ڈیٹس",
"discovery": "دریافت",
"visibility": "مرئیت",
"infrastructure": "انفراسٹرکچر",
"integration": "انضمام",
"notification": "اطلاع",
"immediate": "فوری",
"faster": "زیادہ تیز",
"real-time": "حقیقی وقت",
"crawl": "خزیدن",
"crawling": "خزیدہ کرنا",
"publish": "اشاعت",
"information": "معلومات",
"experience": "تجربہ",
"relevant": "متعلقہ",
"distribute": "تقسیم کرنا",
"growth": "ترقی",
"product": "مصنوعات",
"products": "مصنوعات",
"promotion": "تشہیر",
"promotions": "تشہیری مہمات",
"customer": "گاہک",
"customers": "گاہکوں",
"inventory": "اسٹاک",
"store": "اسٹور",
"merchant": "تاجر",
"merchants": "تاجر حضرات",
"ecommerce": "ای کامرس",
"seo": "ایس ای او",
"organic": "قدرتی",
"traffic": "ٹریفک",
"engagement": "مشغولیت",
"load": "لوڈ",
"redundant": "غیر ضروری",
"schema": "سکیمہ",
"marketing": "مارکیٹنگ",
"initiative": "پہل",
"competitive": "مقابلے کا",
"fast-moving": "تیز رفتار",
"environment": "ماحول",
"tool": "اوزار",
"install": "انسٹال کریں",
"wordpress": "ورڈپریس",
"theme": "تھیم",
"feature": "خصوصیت",
"reader": "قاری",
"readers": "قارئین",
"navigation": "تشریف لے جانا",
"title": "عنوان",
"post": "تحریر",
"posts": "تحریریں",
"comments": "تبصرے",
"section": "حصہ",
"footer": "فوٹر",
"subscribe": "سبسکرائب کریں",
"ideas": "خیالات",
"creativity": "تخلیقیت",
"economy": "معیشت",
"intelligent": "ذہین",
"statistical": "اعدادیاتی",
"patterns": "پیٹرنز",
"semantic": "معنوی",
"culture": "ثقافت",
"expression": "اظہار",
"literacy": "خواندگی"

};


export function translateToUrdu(text: string): string {
  return text.split(" ").map(word => {
    const match = word.match(/^(\w+)([.,!?:;]*)$/i); // separate punctuation
    if (!match) return word;

    const [ , rawWord, punctuation ] = match;
    const translated = urduDictionary[rawWord.toLowerCase()];
    return translated ? translated + punctuation : word;
  }).join(" ");
}
